name: gendiff_actions

on:
  push:
    branches:
      - '**'
    tags:
      - '**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make lint
      - run: make tests

